# Generated by Django 3.2.4 on 2021-06-30 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='complete',
            new_name='is_completed',
        ),
    ]
